# Generated by Django 4.2.15 on 2024-08-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_description', models.TextField()),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event_date', models.DateField(auto_now=True)),
                ('event_time', models.TimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
